version: '3'
services:
  web:
    container_name: web
    build: .
    image: shop:latest
    environment:
      - DATABASE_URL=postgres://santaasus:youShouldChangeThisPassword@db:5432/shop_db?sslmode=disable
    ports:
      - '8080:8080'
    restart: on-failure
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy  

  db:
    container_name: db
    platform: linux/arm64
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'shop_db'
      POSTGRES_USER: 'santaasus'
      POSTGRES_PASSWORD: 'youShouldChangeThisPassword'
    ports:
      - '3306:5432'
    expose:
      - '3306'
    volumes:
      - ./docker/scripts/scheme.sql:/docker-entrypoint-initdb.d/setup.sql
      - pgdata:/var/lib/postgresql/data

    networks:
      - network
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U santaasus -d shop_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes: 
  pgdata:
    
networks:
    network:
      driver: bridge
